namespace: vdolgikh
name: test_createfile
version: 1.0.0
readme: README.md
authors:
- Valentin Dolgikh <valentin.dolgikh@gmail.com>
description: your collection description
license:
- GPL-2.0-or-later
tags: [ create, file, python, ansible, module ]
dependencies: { python >= 3.5 }
repository: https://github.com/vdolgikh/devops-netology
documentation: https://github.com/vdolgikh/devops-netology/blob/main/4_conf-homeworks/conf_06/vdolgikh/test_createfile/README.md