galaxy_info:
  role_name: createfile
  author: Valentin Dolgikh
  description: The role create a file
  company: ---

  license: MIT

  min_ansible_version: 2.10

  platforms:
  - name: EL
    versions:
    - 7
    - 8
  - name: Ubuntu
    versions:
    - all
